site_name: "Openemail Deployers Guide"
site_url: https://openemail.io
copyright: 'Copyright 2019 Chinthaka Deshapriya'
repo_name: openemail/openemail
repo_url: https://github.com/openemail/openemail-docs/
edit_uri: edit/master/docs/
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'
# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/openemail'
    - type: 'twitter'
      link: 'https://twitter.com/openemail'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/openemail'

markdown_extensions:
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - footnotes
nav:
- 'Openemail Overview and Support': 'index.md'
- 'Prerequisites':
  - 'Prepare Your System': 'prerequisite-system.md'
  - 'DNS Setup': 'prerequisite-dns.md'
- 'Installation and Update':
  - 'Installation': 'install.md'
  - 'Update': 'install-update.md'
- 'First Steps':
  - 'SSL': 'firststeps-ssl.md'
  - 'Rspamd Web UI': 'firststeps-rspamd_ui.md'
  - 'Reverse Proxy': 'firststeps-rp.md'
  - 'SNAT': 'firststeps-snat.md'
  - 'Disable IPv6': 'firststeps-disable_ipv6.md'
  - 'Setup A Relayhost': 'firststeps-relayhost.md'
  - 'Logging': 'firststeps-logging.md'
  - 'Local MTA on Docker Host': 'firststeps-local_mta.md'
  - 'Sync Jobs Migration': 'firststeps-sync_jobs_migration.md'
- 'Models':
  - 'Sender and Receiver Model': 'model-sender_rcv.md'
  - 'ACL': 'model-acl.md'
- 'Debugging and Troubleshooting':
    - 'Introduction': 'debug.md'
    - 'Logs': 'debug-logs.md'
    - 'Attach a Container': 'debug-attach_service.md'
    - 'Reset Passwords': 'debug-reset_pw.md'
    - 'Remove Persistent Data': 'debug-rm_volumes.md'
    - 'Common Problems': 'debug-common_problems.md'
- 'Backup and Restore':
  - 'Helper script':
      - 'Backup': 'b_n_r_backup.md'
      - 'Restore': 'b_n_r_restore.md'
  - 'Manually':
      - 'Maildir': 'u_e-backup_restore-maildir.md'
      - 'MySQL': 'u_e-backup_restore-mysql.md'
- 'Usage and Examples':
  - 'Openemail UI':
      - 'Configuration': 'u_e-openemail_ui-config.md'
      - 'Blacklist / Whitelist': 'u_e-openemail_ui-bl_wl.md'
      - 'Spamfilter': 'u_e-openemail_ui-spamfilter.md'
      - 'Temporary Email Aliases': 'u_e-openemail_ui-spamalias.md'
      - 'Tagging': 'u_e-openemail_ui-tagging.md'
      - 'Two-Factor Authentication': 'u_e-openemail_ui-tfa.md'
  - 'Postfix':
      - 'Anonymize Headers': 'u_e-postfix-anonym_headers.md'
      - 'Disable Sender Addresses Verification': 'u_e-postfix-disable_sender_verification.md'
      - 'Maximum Message Size or Attachment Size': 'u_e-postfix-attachment_size.md'
      - 'Statistics with Pflogsumm': 'u_e-postfix-pflogsumm.md'
  - 'Unbound':
      - 'Using An External DNS Service': 'u_e-unbound-fwd.md'
  - 'Dovecot':
      - "Enable Any and All Authenticated ACL Settings": 'u_e-dovecot-any_acl.md'
      - "Expunge a User's Mails": 'u_e-dovecot-expunge.md'
      - 'Mail Crypt': 'u_e-dovecot-mail-crypt.md'
      - 'More Examples with DOVEADM': 'u_e-dovecot-more.md'
      - 'Move Vmail Volume': 'u_e-dovecot-vmail-volume.md'
      - 'IMAP IDLE Interval': 'u_e-dovecot-idle_interval.md'
      - 'FTS and Solr': 'u_e-dovecot-fts.md'
  - 'Nginx': 'u_e-nginx.md'
  - 'Redis': 'u_e-redis.md'
  - 'Rspamd': 'u_e-rspamd.md'
  - 'SOGo': 'u_e-sogo.md'
  - 'Docker':
      - 'Customize Dockerfiles': 'u_e-docker-cust_dockerfiles.md'
      - 'Docker Compose Bash Completion': 'u_e-docker-dc_bash_compl.md'
  - 'Why unbound?': 'u_e-why_unbound.md'
  - 'Autodiscover and  Autoconfig': 'u_e-autodiscover_config.md'
  - 'Redirect HTTP to HTTPS': 'u_e-80_to_443.md'
  - 'Adjust Service Configurations': 'u_e-change_config.md'
  - 'Deinstall': 'u_e-deinstall.md'
- 'Client Configuration':
  - 'Overview': 'client.md'
  - 'Android': 'client/client-android.md'
  - 'Apple macOS / iOS': 'client/client-apple.md'
  - 'eM Client': 'client/client-emclient.md'
  - 'KDE Kontact': 'client/client-kontact.md'
  - 'Microsoft Outlook': 'client/client-outlook.md'
  - 'Mozilla Thunderbird': 'client/client-thunderbird.md'
  - 'Windows Mail': 'client/client-windows.md'
  - 'Windows Phone': 'client/client-windowsphone.md'
  - 'Manual configuration': 'client/client-manual.md'
- 'Third Party Apps':
  - 'SOGo Integrator for Thunderbird': 'third_party-thunderbird.md'
  - 'Roundcube': 'third_party-roundcube.md'
  - 'Portainer': 'third_party-portainer.md'
  - 'Gogs': 'third_party-gogs.md'
  - 'Gitea': 'third_party-gitea.md'
- 'Nextcloud Integration':
   - 'Introduction': 'nextcloud-Introduction.md'
   - 'Nextcloud for Your Business': 'nextcloud-for-business.md'
extra:
  logo: 'images/logo.png'
  social:
    - type: globe
      link: https://openemail.io
    - type: github-alt
      link: https://docs.openemail.io
plugins:
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
extra_css: [extra.css]
extra_javascript: [clients.js]
google_analytics: ['UA-136239070-1', 'openemail.io']
