site_name: "RAVANOS Documentation"
site_url: https://wiki.ravanos.org/
copyright: 'Copyright 2019 Chinthaka Deshapriya and RAVANOS.ORG'
repo_name: ravanos/ravanos.github.io
repo_url: https://github.com/openemail/openemail-docs/
edit_uri: edit/master/docs/
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'
# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/ravanos'
    - type: 'twitter'
      link: 'https://twitter.com/ravanos'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/ravanos'

markdown_extensions:
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - footnotes
nav:
- 'RavanOS Common Linux Edition': 'index.md'
- 'Installation, configuration, maintenance OS':
  - 'OS Installation Guide': 'prerequisite-system.md'
extra:
  logo: 'images/ravanoslogo.png'
  social:
    - type: globe
      link: https://wiki.ravanos.org
    - type: github-alt
      link: https://docs.ravanos.org
plugins:
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
extra_css: [extra.css]
extra_javascript: [clients.js]
google_analytics: ['UA-136239070-1', 'wiki.ravanos.org']
